spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${EUREKA_INSTANCE_IP:127.0.0.1}

