server:
  tomcat:
    threads:
      max: 10
      min-spare: 1
    max-connections: 50
    accept-count: 20

eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${EUREKA_INSTANCE_IP:127.0.0.1}
  client:
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:${EUREKA_SERVER_URL:http://127.0.0.1:8761/eureka/}}

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:safebus}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USER:root}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:sathish@6064}}
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      idle-timeout: 30000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    baseline-on-migrate: true
  amqp:
    deserialization:
      trust:
        all: true
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:${RABBITMQ_HOST:localhost}}
    port: ${SPRING_RABBITMQ_PORT:${RABBITMQ_PORT:5672}}
    username: ${SPRING_RABBITMQ_USERNAME:${RABBITMQ_USERNAME:guest}}
    password: ${SPRING_RABBITMQ_PASSWORD:${RABBITMQ_PASSWORD:guest}}


# Global Swagger Enabled by Default (Local/Dev)
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
  paths-to-match: /api/v1/**
cv:
  confidence-threshold: 0.80

storage:
  location: ${STORAGE_LOCATION:/app/uploads}

idcard:
  storage-location: ${STORAGE_LOCATION:/app/uploads}

---
spring:
  config:
    activate:
      on-profile: prod

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
