"""Add school_email column to Student model

Revision ID: 491472367486
Revises: a1cb3a294766
Create Date: 2026-07-30 18:41:43.103465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '491472367486'
down_revision = 'a1cb3a294766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_email', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['school_email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('school_email')

    # ### end Alembic commands ###
