"""Add SOS emergency system

Revision ID: 7caeb24ab53e
Revises: 
Create Date: 2026-07-30 15:37:41.101078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7caeb24ab53e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sos_id', sa.String(length=50), nullable=False),
    sa.Column('recipient_type', sa.String(length=50), nullable=False),
    sa.Column('recipient_name', sa.String(length=150), nullable=False),
    sa.Column('delivery_method', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='deliverystatus'), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('error_message', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_logs_sos_id'), ['sos_id'], unique=False)

    op.create_table('police_stations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sos_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sos_id', sa.String(length=50), nullable=False),
    sa.Column('bus_id', sa.String(length=50), nullable=False),
    sa.Column('driver_id', sa.String(length=100), nullable=False),
    sa.Column('driver_name', sa.String(length=150), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('route_name', sa.String(length=150), nullable=True),
    sa.Column('emergency_type', sa.String(length=150), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'POLICE_NOTIFIED', 'ADMIN_ACKNOWLEDGED', 'RESOLVED', name='sosstatus'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='sosseverity'), nullable=False),
    sa.Column('is_test', sa.Boolean(), nullable=False),
    sa.Column('police_station_id', sa.Integer(), nullable=True),
    sa.Column('parent_notified', sa.Boolean(), nullable=False),
    sa.Column('admin_notified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=100), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sos_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sos_alerts_bus_id'), ['bus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sos_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sos_alerts_sos_id'), ['sos_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_sos_alerts_status'), ['status'], unique=False)

    op.create_table('sos_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sos_id', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('performed_by', sa.String(length=150), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('device', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sos_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sos_audit_logs_sos_id'), ['sos_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sos_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sos_audit_logs_sos_id'))

    op.drop_table('sos_audit_logs')
    with op.batch_alter_table('sos_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sos_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_sos_alerts_sos_id'))
        batch_op.drop_index(batch_op.f('ix_sos_alerts_created_at'))
        batch_op.drop_index(batch_op.f('ix_sos_alerts_bus_id'))

    op.drop_table('sos_alerts')
    op.drop_table('police_stations')
    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_logs_sos_id'))

    op.drop_table('notification_logs')
    # ### end Alembic commands ###
