"""Add ID card columns to Student model

Revision ID: a1cb3a294766
Revises: c410c80a1821
Create Date: 2026-07-30 18:39:26.638391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1cb3a294766'
down_revision = 'c410c80a1821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_card_front_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('id_card_back_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('id_card_pdf_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('id_card_generated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('id_card_version', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('id_card_status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('id_card_status')
        batch_op.drop_column('id_card_version')
        batch_op.drop_column('id_card_generated_at')
        batch_op.drop_column('id_card_pdf_path')
        batch_op.drop_column('id_card_back_path')
        batch_op.drop_column('id_card_front_path')

    # ### end Alembic commands ###
