"""Add account provisioning and credential audits

Revision ID: c064dc17dea0
Revises: 491472367486
Create Date: 2026-07-30 20:52:09.883558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c064dc17dea0'
down_revision = '491472367486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credential_audits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('generated_by', sa.String(length=100), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('credential_type', sa.String(length=50), nullable=False),
    sa.Column('first_login_completed', sa.Boolean(), server_default='0', nullable=True),
    sa.Column('download_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('printed_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('status', sa.String(length=50), server_default='ACTIVE', nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), server_default='1', nullable=True))
        batch_op.add_column(sa.Column('last_password_change', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('account_status', sa.String(length=50), server_default='ACTIVE', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('account_status')
        batch_op.drop_column('last_password_change')
        batch_op.drop_column('must_change_password')

    op.drop_table('credential_audits')
    # ### end Alembic commands ###
