"""Add student registration and attendance logging tables

Revision ID: c410c80a1821
Revises: 7caeb24ab53e
Create Date: 2026-07-30 17:43:33.683007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c410c80a1821'
down_revision = '7caeb24ab53e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('father_name', sa.String(length=150), nullable=False),
    sa.Column('mother_name', sa.String(length=150), nullable=False),
    sa.Column('guardian_name', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('student_sequences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('bus_id', sa.String(length=50), nullable=False),
    sa.Column('driver_name', sa.String(length=150), nullable=False),
    sa.Column('scan_time', sa.String(length=50), nullable=False),
    sa.Column('scan_date', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('attendance_type', sa.String(length=50), nullable=False),
    sa.Column('trip_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_logs', schema=None) as batch_op:
        batch_op.create_index('idx_attendance_logs_lookup', ['student_id', 'scan_date', 'trip_id', 'bus_id', 'status'], unique=False)

    op.create_table('parent_notification_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('notification_type', sa.String(length=100), nullable=False),
    sa.Column('delivery_method', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('event_name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('admission_no', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('dob', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('section', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('photo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('route_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('pickup_stop_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('qr_code_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('qr_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('student_status', sa.String(length=50), nullable=True))
        batch_op.create_index('idx_students_parent_id', ['parent_id'], unique=False)
        batch_op.create_index('idx_students_student_status', ['student_status'], unique=False)
        batch_op.create_unique_constraint('uq_students_qr_token', ['qr_token'])
        batch_op.create_unique_constraint('uq_students_admission_no', ['admission_no'])
        batch_op.create_unique_constraint('uq_students_student_id', ['student_id'])
        batch_op.create_foreign_key('fk_students_parent_id', 'parents', ['parent_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint('fk_students_parent_id', type_='foreignkey')
        batch_op.drop_constraint('uq_students_qr_token', type_='unique')
        batch_op.drop_constraint('uq_students_admission_no', type_='unique')
        batch_op.drop_constraint('uq_students_student_id', type_='unique')
        batch_op.drop_index('idx_students_student_status')
        batch_op.drop_index('idx_students_parent_id')
        batch_op.drop_column('student_status')
        batch_op.drop_column('qr_token')
        batch_op.drop_column('qr_code_path')
        batch_op.drop_column('pickup_stop_id')
        batch_op.drop_column('route_id')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('photo')
        batch_op.drop_column('section')
        batch_op.drop_column('dob')
        batch_op.drop_column('gender')
        batch_op.drop_column('admission_no')
        batch_op.drop_column('student_id')

    op.drop_table('student_events')
    op.drop_table('parent_notification_logs')
    op.drop_table('attendance_logs')
    op.drop_table('student_sequences')
    op.drop_table('parents')
    # ### end Alembic commands ###
