"""Extend account and credential audit models

Revision ID: c6fb32662865
Revises: c064dc17dea0
Create Date: 2026-08-06 09:58:06.523511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6fb32662865'
down_revision = 'c064dc17dea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_version', sa.Integer(), server_default='1', nullable=True))
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('lock_time', sa.DateTime(), nullable=True))

    with op.batch_alter_table('credential_audits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('password_changed', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ip_address', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('browser', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('device', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credential_audits', schema=None) as batch_op:
        batch_op.drop_column('device')
        batch_op.drop_column('browser')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('password_changed')
        batch_op.drop_column('reset_time')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('lock_time')
        batch_op.drop_column('created_by')
        batch_op.drop_column('last_login')
        batch_op.drop_column('failed_login_attempts')
        batch_op.drop_column('password_version')

    # ### end Alembic commands ###
